### ISSUE TITLE
Differences between Carbon-Router and Iron-Router

### ISSUE THREAD

**Issue by jakobrosenberg** [gfk-ba/carbon-router#1]
Any chance you can elaborate on the differences between Carbon-Router and Iron-Router? With Iron-Router being the de facto router for Meteor projects, it would be nice to see a brief description of how Carbon-Router differs.

**Comment by krawalli** [comment]
url parameters are not supported (yet)?

**Comment by marcodejongh** [comment]
@krawalli What kind of url parameters do you mean? 

```
  Router.add('item', '/item/{itemId}', {
    regions: {
      content: {
        template: 'item',
        data: function(data) {
          return {item: items[data.itemId]};
        }
      }
    }
  });
```
In the item template  you will have access to ```item```

**Comment by krawalli** [comment]
you mean *itemId*.

And that's what I wanted to know
