### ISSUE TITLE
Controller.callBeforeHook not called anywhere?

### ISSUE THREAD

**Issue by russellfeeed** [gfk-ba/carbon-router#2]
HI

I have a simple route which needs a check to be run before the route is followed: If a token is not present I need to redirect the user to an error page.

```
Router.add('shopfront', '/enter/{token}', {
   before:  function(data) {
                     exlogger('shopfront:'+data);
                     
                     if (data.token)            
                       Session.set('authtoken', data.token);
                     else
                       if (!Session.get('authtoken')) 
                         Router.go('noentry');
                        
                   },
    regions: {       
      content: {
        template: 'shopfront',
      }
    }
  });
```

I have traced this in Firebug and I cannot see my 'exlogger' being called so I believe the "before" function is not being called.

Looking in https://github.com/gfk-ba/carbon-router I can only see Controller.callBeforeHook being called in TinyTest routines.

thanks
Russell

**Comment by marcodejongh** [comment]
@russellfeeed The bugfix was merged to master and will be published under the gfk maintainer so use ```meteor add gfk:carbon-router``` to add it to your project
