### ISSUE TITLE
Is there anyway to handle anchor tags?

### ISSUE THREAD

**Issue by mesosteros** [gfk-ba/carbon-router#5]
Say I have an icon that when clicked should simply head to the anchor tag .
Usually I would write it as:
<a href="#anchorToGoTo" class="down-arrow"></a>
Does Carbon have anyway to handle these anchors?

**Comment by marcodejongh** [comment]
@mesosteros we will no longer maintain this project. I suggest you have a look at https://github.com/meteorhacks/flow-router. Or fork the project and implement whatever you need yourself

**Comment by mesosteros** [comment]
Very sorry to hear that. Carbon was fantastic because of the easiness to use. Flow is quite a bit more hectic.
Thank you anyway :wine_glass:

**Comment by marcodejongh** [comment]
@mesosteros feel free to keep on using it. I doubt it will break.
